### ISSUE TITLE
Update Idno -> Known in the sponsors at the bottom of the page

### ISSUE THREAD

**Issue by kylewm** [indieweb/wiki#20]

**Comment by aaronpk** [comment]
do you think it's appropriate to rename it, or add Known as a new one?

**Comment by kylewm** [comment]
No clue! We should ask @benwerd @erinjo

**Comment by benwerd** [comment]
I'd say this is up to the IndieWebCamp organizers - happy to go in either direction. Very happy to supply images and so on. 

Thanks for bringing this up @kylewm!

cc @erinjo

**Comment by kylewm** [comment]
Aaronpk brought it up in the IRC channel, I was just reminding him :)

**Comment by aaronpk** [comment]
The new wiki skin does not list sponsors in the footer of every page.
