### ISSUE TITLE
Don’t style the colour of form inputs

### ISSUE THREAD

**Issue by jonnybarnes** [indieweb/wiki#21]
This is me searching for `test` on the wiki:
![default search](https://cloud.githubusercontent.com/assets/108303/13900065/77c286e2-edf5-11e5-9306-961a2f0aa4af.png)

Now with the `color` style removed:
![search without color style](https://cloud.githubusercontent.com/assets/108303/13900071/a7b74342-edf5-11e5-98d6-f6ecbe54f271.png)

Don’t hate those of us with dark themes

**Comment by aaronpk** [comment]
This is no longer the case with the Vector skin.
