### ISSUE TITLE
[css] diffs sometimes becoming hidden

### ISSUE THREAD

**Issue by ghost** [indieweb/wiki#23]
wiki needs responsive css layout maybe?

atm `table.diff` is direct child of the `div` which holds entire article, so `overflow:scroll` will also scroll everything else :(

http://indiewebcamp.com/wiki/index.php?title=authorship&action=historysubmit&diff=26777&oldid=15823

![screen shot 2016-04-08 at 22 41 56](https://cloud.githubusercontent.com/assets/9968388/14397170/247cc9f6-fddc-11e5-8d93-54a66e848d13.jpg)
![screen shot 2016-04-08 at 22 47 33](https://cloud.githubusercontent.com/assets/9968388/14397169/24721ab0-fddc-11e5-9d89-92a69cb23f24.jpg)

**Comment by aaronpk** [comment]
This is no longer the case on the new Vector skin.
