### ISSUE TITLE
Logins should use the person's authorization endpoint if specified

### ISSUE THREAD

**Issue by aaronpk** [indieweb/wiki#28]
If the user has specified an authorization endpoint on their home page, the wiki should use that directly rather than letting indieauth.com handle it. This will change the wiki's use of indieauth.com to be only used for rel-me-auth handling. 

If you've defined your own authorization endpoint then you will never hit indieauth.com when signing in.

**Comment by barryf** [comment]
This just tripped me up. I'm unable to use IndieAuth.com and so my homepage specifies my own auth endpoint which the wiki doesn't follow.

**Comment by aaronpk** [comment]
Why are you unable to use indieauth.com? IndieAuth.com should be finding your own auth endpoint.

**Comment by barryf** [comment]
The IndieAuth.com server just doesn't like my site (or something about its SSL cert): https://github.com/aaronpk/IndieAuth.com/issues/148

**Comment by aaronpk** [comment]
This was resolved once the wiki switched to indielogin.com for logins!
