### ISSUE TITLE
consider very light color backgrounds for each homepage section

### ISSUE THREAD

**Issue by tantek** [indieweb/wiki#31]
Similar to our existing "What is the IndieWeb" section, and block sections on http://habariproject.org/en/ - let's consider very light color backgrounds for each homepage section for easier mental/visual "chunking".

**Comment by aaronpk** [comment]
@veganstraightedge Do you have any guidelines on a color scheme we could use? The current IWC colors are super bold, so we'd need some sort of matching lighter color scheme to add to the branding guidelines.

**Comment by colintedford** [comment]
For freer color choice, could put the text of each section in white box on top of the colored background as http://www.bbc.com/ does (they have little boxes and only use gray & white backgrounds, but you get the idea).

**Comment by veganstraightedge** [comment]
I don't have any other colors currently.

**Comment by aaronpk** [comment]
I used a tool that @veganstraightedge recommended to generate a color palette based off of our current red/orange/yellow color scheme: https://github.com/okayjeffrey/Scalor This is a good start for alternate shades of the colors within the scheme.

<img width="1143" alt="screenshot 2016-07-05 17 32 25" src="https://cloud.githubusercontent.com/assets/113001/16605429/b5abc0fc-42e3-11e6-8d65-9ae39aea1928.png">

**Comment by aaronpk** [comment]
I just made a first attempt at this on the home page! Check it out, and feel free to suggest changes or just make edits! https://indieweb.org/

**Comment by colintedford** [comment]
"Join" & "Beyond" were a little hard to read b/c low contrast. Tried lighter shades but they didn't seem right for the boldness of the content. Tried darker color w/ white text but then the links were hard to see. Went w/ white box for content on colored background -- not convinced it's the way, but it's more readable.

Also added color to HWC & IWC sections & padding to the last sections.

**Comment by aaronpk** [comment]
How about white text and links?

<img src="https://aaronparecki.com/media/file-20160706035722-37577.png">

**Comment by colintedford** [comment]
The (logged-out) sign-in looks a bit weird as an unstyled box in the corner of the black "What is the Indieweb?" box.

**Comment by colintedford** [comment]
White text looks good. Links are hard to see -- maybe underline them?

**Comment by tantek** [comment]
Looking at https://indieweb.org/ today it looks like this problem is solved, and readably so. Closing this issue accordingly. Feel free to re-open if you think otherwise, or if there are specific nitpicks (like one section in particular you want a different color), please open a new issue for that.

**Comment by aaronpk** [comment]
For posterity's sake, here's what the page looks like today:
<img width="861" alt="screenshot 2016-07-08 10 46 38" src="https://cloud.githubusercontent.com/assets/113001/16696336/4add4170-44f9-11e6-81de-b199ebe75443.png">
