### ISSUE TITLE
our custom home page needs "Login" link in top right like every other page

### ISSUE THREAD

**Issue by tantek** [indieweb/wiki#38]
It's confusing right now (just observed at IndieWebCamp LA 2016) for new IndieWeb community members when they go to indieweb.org and see no place to log in.

Totally unobvious that you have to click on a specific page before you log-in.

So the home page should have the same "Login" link in the top right as every other page does

**Comment by gRegorLove** [comment]
Perhaps combine with #36 to include a login button at the top right of the "next IWC" banner.

**Comment by aaronpk** [comment]
This was fixed by editing the CSS embedded in the home page 

https://indieweb.org/wiki/index.php?title=Main_Page&diff=40158&oldid=40039
