### ISSUE TITLE
indieweb.org/live doesn't work

### ISSUE THREAD

**Issue by sknebel** [indieweb/wiki#44]
I could have Kaja take care of it, since it is looking for streams anyways, or is the existing mechanism trivial to fix?

**Comment by aaronpk** [comment]
I don't actually have an automatic mechanism for updating this. If you had a public endpoint on Kaja I could hit to return the current video, I can integrate that.

**Comment by sknebel** [comment]
I can expose that, but I think I could just have Kaja edit the /live page and put a direct youtube embed (or even multiple ones for parallel sessions) there.

**Comment by aaronpk** [comment]
Good point! I'd say just go ahead and do that then!

**Comment by aaronpk** [comment]
kaja has been doing this now! https://indieweb.org/wiki/index.php?title=live&action=history
