### ISSUE TITLE
do something about viewing times in local time

### ISSUE THREAD

**Issue by sknebel** [indieweb/wiki#47]
I apologize for not very inventive title. When following events remotely converting between timezones can be a bit annoying ("When does the Demo stream start?", "When is vHWC in my timezone"). Thus I'm asking for ideas how to handle this nicely. A few ideas:
* special element that displays local time and maybe countdown
* button to convert times to local time 
* display converted time in <title>
* move to IRC, let a bot answer questions like "How long until 16:30 in Austin?"

This potentially could be done with site-wide Javascript as a pure enhancement, selecting events with some kind of special markup.

The biggest issue I see is getting the timezone. It's often not marked up and Lookup on the basis of locations (which Kaja attempts to do when trying to figure out when IWC streams might be happening) only works for some events and not easily done client-side. Time is often only marked up as mf2-enhanced text.

**Comment by gRegorLove** [comment]
Maybe relevant:
https://en.wikipedia.org/wiki/Wikipedia:Comments_in_Local_Time
https://en.wikipedia.org/wiki/User:Mxn/CommentsInLocalTime

**Comment by aaronpk** [comment]
I'm going to close this since we moved events off the wiki!

**Comment by sknebel** [comment]
looking at a detailed session grid in the wiki for a current event right now ;)
