### ISSUE TITLE
Give error message to users logging in with banned domains

### ISSUE THREAD

**Issue by sknebel** [indieweb/wiki#48]
At least for the blanket-bans of entire services there should be an error message instead of silently not logging-in the user. Just had a question about someone not being able to log in and I only randomly had a hunch that github.io might be blocked.

(block list currently at https://github.com/indieweb/mediawiki-extensions/blob/master/LassoAuth.php#L17 )

**Comment by sknebel** [comment]
It seems like the mediawiki-extension has no hook or other way for showing an error when the blacklist is hit. We could either try to get that changed, or maybe enforce the blocklist somewhere in the lasso flow instead.

**Comment by aaronpk** [comment]
It's not the prettiest, but the wiki now shows this when someone logs in with a blocked domain.

![Screen Shot 2020-08-31 at 7 03 43 AM](https://user-images.githubusercontent.com/113001/91728586-26461d00-eb58-11ea-86a1-1d23c64c3636.png)
