### ISSUE TITLE
Secret login with password form

### ISSUE THREAD

**Issue by kartikprabhu** [indieweb/wiki#49]
There seems to be a secret login page with Username and password fields https://indieweb.org/wiki/index.php?title=Special:UserLogin&returnto=Special%3AUpload

perhaps https://indieweb.org/wiki/index.php?title=Special:UserLogin&returnto=XYZ should redirect to https://sso.indieweb.org/login?url=https://indieweb.org/XYZ

ref: https://chat.indieweb.org/2019-05-21#t1558482428958800

**Comment by aaronpk** [comment]
This is disabled now by adding custom text to the login page 

https://indieweb.org/MediaWiki:Loginprompt
