### ISSUE TITLE
Adding info about the Murmurations standard to IndieWeb.org

### ISSUE THREAD

**Issue by strypey** [indieweb/wiki#50]
Not sure where to introduce this, but I did a web search and couldn't find any info about IndieWeb use of the fairly new Murmurations standard, a kind of FOAF developed for mapping the solidarity economy, but useful to anyone who wants to make info about their organizations and projects more widely available:
https://murmurations.network/

**Comment by aaronpk** [comment]
Thanks, this repo isn't for adding things to the wiki, it's for tracking issues about the wiki itself. The wiki lives at https://indieweb.org 

If you are using this on your personal website then you're welcome to add it to the wiki yourself!
