### ISSUE TITLE
Fix live search on Vector 2022 theme

### ISSUE THREAD

**Issue by paulrobertlloyd** [indieweb/wiki#52]
Currently, no results are returned in the live search when the Vector 2022 skin is chosen. Inspecting the page, a 404 is returned for the following (for a search query of `test`):

```
https://indieweb.org/wiki/rest.php/v1/search/title?q=test&limit=10
```

Here’s how it behaves (the progress bar continues to pulse, but no results are returned):

<img width="530" alt="Screenshot of live search not returning any results." src="https://github.com/indieweb/wiki/assets/813383/f1d97c93-21e1-4f3c-8ded-88bc73d41eeb">

Might this be because we have redirects to prevent URLs from including `/wiki`

**Comment by aaronpk** [comment]
Turns out the MW docs have special handling for their strange use of putting a path after the `rest.php` path.

https://www.mediawiki.org/wiki/Manual:Short_URL/Nginx

Fixed now!

**Comment by paulrobertlloyd** [comment]
Yay! Thanks @aaronpk.
